version: '3'
services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=segmentation
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@example.com
      PGADMIN_DEFAULT_PASSWORD: mypassword

  segmentation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./segmentation"]
    environment:
      HTTP_ADDR: ":9090"
      PG_URL: "postgres://postgres:postgres@postgres/segmentation?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/pg/migrations"